"""Text measurement for the hand-built SVG diagrams.

The flowchart used to guess node sizes (fixed 300px boxes, fixed 184x88
diamonds), which is why long labels spilled out of their shapes and rows of
three nodes overlapped. Everything here answers one question instead:
*how wide is this string, in this style, in px?* — using advance widths read
straight out of the woff2 files the page actually serves
(``font_metrics.py``, generated by ``tools/gen_font_metrics.py``).

Styles are keyed by the CSS class the renderer emits, so a font-size change in
``diagram.css`` only has to be mirrored in ``STYLES`` and every size and wrap
decision follows.
"""
from __future__ import annotations

from .font_metrics import MONO, MONO_FALLBACK, SANS_400, SANS_600, SANS_700


class Style:
    """A (font table, size, line height) triple matching one CSS class."""

    __slots__ = ("table", "fallback", "size", "line_h")

    def __init__(self, table: dict[str, float], fallback: float,
                 size: float, line_h: float) -> None:
        self.table = table
        self.fallback = fallback
        self.size = size
        self.line_h = line_h


# Keep in sync with .annotate-flow rules in static/diagram.css.
STYLES: dict[str, Style] = {
    "flow-label":       Style(SANS_600, SANS_600["x"], 13.5, 18),
    "flow-label-error": Style(SANS_700, SANS_700["x"], 13.0, 18),
    "flow-ref":         Style(MONO, MONO_FALLBACK, 12.0, 16),
    "flow-method":      Style(MONO, MONO_FALLBACK, 11.5, 16),
    "flow-sub":         Style(SANS_400, SANS_400["x"], 11.0, 15),
    "edge-label":       Style(SANS_600, SANS_600["x"], 11.0, 14),
    # .annotate-seq
    "actor-label":      Style(SANS_600, SANS_600["x"], 11.0, 14),
    "arrow-label":      Style(SANS_600, SANS_600["x"], 11.0, 14),
    "arrow-sub":        Style(SANS_400, SANS_400["x"], 9.5, 12),
}


def text_px(text: str, style: str) -> float:
    """Width of ``text`` in px when rendered in ``style``."""
    st = STYLES[style]
    total = 0.0
    for ch in text:
        total += st.table.get(ch, st.fallback)
    return total * st.size


def line_h(style: str) -> float:
    return STYLES[style].line_h


def wrap(text: str, style: str, max_px: float) -> list[str]:
    """Greedy word-wrap ``text`` so each line fits ``max_px``.

    Words longer than ``max_px`` are left intact on their own line — breaking
    an identifier mid-token is exactly the Mermaid behaviour this renderer
    exists to avoid. Callers size the shape from the returned lines, so an
    over-long word widens the node rather than overflowing it.
    """
    words = text.split()
    if not words:
        return [""]
    lines: list[str] = []
    cur = words[0]
    for w in words[1:]:
        cand = f"{cur} {w}"
        if text_px(cand, style) <= max_px:
            cur = cand
        else:
            lines.append(cur)
            cur = w
    lines.append(cur)
    return lines
