"""Generate skills/annotate/diagrams/font_metrics.py from the bundled woff2 fonts.

Run offline with fontTools installed; the generated module is pure data so the
skill itself keeps zero third-party runtime dependencies.
"""
import sys
from pathlib import Path

from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

REPO = Path(__file__).resolve().parents[0]
FONTS = Path(sys.argv[1])
OUT = Path(sys.argv[2])

# printable ASCII + a few glyphs that show up in code refs / labels
CHARS = [chr(c) for c in range(32, 127)] + list("—–…·→✓×≤≥")


def widths_for(font_path: Path, wght: float | None) -> tuple[dict[str, float], float]:
    f = TTFont(font_path)
    if wght is not None and "fvar" in f:
        f = instantiateVariableFont(f, {"wght": wght}, updateFontNames=False)
    upem = f["head"].unitsPerEm
    cmap = f.getBestCmap()
    hmtx = f["hmtx"]
    out = {}
    for ch in CHARS:
        g = cmap.get(ord(ch))
        if g is None:
            continue
        out[ch] = round(hmtx[g][0] / upem, 4)
    fallback = round(hmtx[cmap[ord("x")]][0] / upem, 4)
    return out, fallback


def emit(name: str, table: dict[str, float], fallback: float) -> str:
    items = ",".join(f"{ch!r}:{w}" for ch, w in sorted(table.items()))
    return f"{name}_FALLBACK = {fallback}\n{name} = {{{items}}}\n\n"


def main() -> None:
    body = [
        '"""Per-character advance widths (in em) for the fonts bundled with the\n'
        "web companion. GENERATED by tools/gen_font_metrics.py — do not hand-edit.\n\n"
        "Values are advance width / unitsPerEm, so px width = sum(widths) * font_size.\n"
        'Bricolage Grotesque is variable; regular (400) and semibold (600) instances\n'
        'are extracted separately because the flowchart uses both.\n"""\n\n',
    ]
    sans = FONTS / "BricolageGrotesque-Variable.woff2"
    mono = FONTS / "MonaspaceRadon-Regular.woff2"
    t, fb = widths_for(sans, 400)
    body.append(emit("SANS_400", t, fb))
    t, fb = widths_for(sans, 600)
    body.append(emit("SANS_600", t, fb))
    t, fb = widths_for(sans, 700)
    body.append(emit("SANS_700", t, fb))
    t, fb = widths_for(mono, None)
    body.append(emit("MONO", t, fb))
    OUT.write_text("".join(body))
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


main()
